name: dotnet project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore '**/*.sln'

      - name: Build solution
        run: dotnet build '**/*.sln' --configuration Release --no-restore

      - name: Run tests
        run: dotnet test '**/*.sln' --configuration Release --no-restore --logger "trx;LogFileName=test_results.trx"

      - name: Publish test results
        uses: actions/upload-artifact@v3
        with:
          name: Test Results
          path: '**/*.trx'
